baseURL = "http://example.org/"
languageCode = "fr_fr"
title = "Hugo"
theme = "ananke"

[[permalinks]]
  posts ="/:year/:month/:day/:title/"
  page ="/:title"


[[menu.main]]
    name ="About"
    url = "/page/about/"

[[menu.main]]
    name ="Lien externe"
    url ="https://www.google.fr"
